name: growmee
description: "A new Flutter project."
publish_to: 
version: 1.0.0+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  provider: ^6.1.1
  get: ^4.7.2
  local_auth: 2.3.0
  get_storage: 2.1.1
  fl_chart: ^1.0.0
  cupertino_icons: ^1.0.8
  flutterfire_cli: ^1.2.0
  real_time_chart: ^0.0.1
  path_provider: ^2.1.5
  http: ^1.4.0
  foundation: ^0.0.5
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.7+1
  uuid: ^4.5.1
dev_dependencies:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Icon apk/Logo GrowME.png"
  min_sdk_android: 21
  
  flutter_test:
    sdk: flutter_test
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/img/Logo GrowME.png

