name : GrowME
description: "A new Flutter project."
publish_to: 'none' # Recommended: set to 'none' to prevent accidental publishing.
version: 1.1.01+16

environment:
  # Menaikkan versi SDK ke yang lebih modern dan stabil
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  in_app_update: ^4.2.3
  provider: ^6.1.1
  get: ^4.6.6 # Sedikit update versi
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3 # Sedikit update versi
  path_provider: ^2.1.3 # Sedikit update versi
  uuid: ^4.4.0 # Sedikit update versi
  http: ^1.2.1 # Sedikit update versi
  url_launcher: ^6.2.6 # Sedikit update versi
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0 # Versi stabil

  # UI
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0 # Versi terbaru
  flutter_markdown: ^0.7.1 # Versi terbaru

  # Lain-lain
  local_auth: ^2.2.0 # Versi terbaru

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versi stabil

  # FlutterFire CLI adalah dev dependency
  flutterfire_cli: ^1.3.1 

  # Konfigurasi launcher icons ditempatkan di sini
  flutter_launcher_icons: ^0.13.1 # Versi stabil

# Konfigurasi untuk flutter_launcher_icons diletakkan di luar dev_dependencies
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Icon apk/Logo GrowME.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/Logo_GrowME.png