// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJYIeKvHvI6cmFZNk5g0OOLK4Q1NWWsFg',
    appId: '1:476364534423:web:b5f3648f38e8d86c346fd2',
    messagingSenderId: '476364534423',
    projectId: 'coba-fee10',
    authDomain: 'coba-fee10.firebaseapp.com',
    storageBucket: 'coba-fee10.firebasestorage.app',
    measurementId: 'G-SP2K319FYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXpzpouVy43WILWRsOVvLJI6RPi-r9AJ0',
    appId: '1:476364534423:android:da347e8b7bf0d7de346fd2',
    messagingSenderId: '476364534423',
    projectId: 'coba-fee10',
    storageBucket: 'coba-fee10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Zud622m_ukNbhg6-97fJqqC3VkPqqaA',
    appId: '1:476364534423:ios:a47b8c648ae3fdeb346fd2',
    messagingSenderId: '476364534423',
    projectId: 'coba-fee10',
    storageBucket: 'coba-fee10.firebasestorage.app',
    iosBundleId: 'com.example.growmee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Zud622m_ukNbhg6-97fJqqC3VkPqqaA',
    appId: '1:476364534423:ios:a47b8c648ae3fdeb346fd2',
    messagingSenderId: '476364534423',
    projectId: 'coba-fee10',
    storageBucket: 'coba-fee10.firebasestorage.app',
    iosBundleId: 'com.example.growmee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJYIeKvHvI6cmFZNk5g0OOLK4Q1NWWsFg',
    appId: '1:476364534423:web:ae136b0850d1ce16346fd2',
    messagingSenderId: '476364534423',
    projectId: 'coba-fee10',
    authDomain: 'coba-fee10.firebaseapp.com',
    storageBucket: 'coba-fee10.firebasestorage.app',
    measurementId: 'G-DSTD9T6RSF',
  );

}